Remove blob
iotaledger/wasp pull request #233
Opened 2024-09-17 13:53 UTC by cwarnerdev

2024-09-27 16:22 UTC, howjmay requested changes

2024-09-27 16:22 UTC, howjmay commented on tools/wasp-cli/chain/deploycontract.go
>  			initParams := util.EncodeParams(args[4:], chainID)
If we removed the description field, we may need to change the index of args here too?
```diff
- initParams := util.EncodeParams(args[4:], chainID)
+ initParams := util.EncodeParams(args[3:], chainID)
```

2024-09-27 16:22 UTC, howjmay commented on tools/wasp-cli/chain/deploycontract.go
>  				log.Check(err)
And 
```diff
- progHash, err = hashing.HashValueFromHex(args[3])
+ progHash, err = hashing.HashValueFromHex(args[2])
```

2024-09-27 17:05 UTC, dessaya approved these changes

2024-09-27 17:05 UTC, dessaya commented on packages/origin/origin.go
> +	accounts.NewStateWriter(v, accounts.Contract.StateSubrealm(d)).SetInitialState(originDeposit)
`baseTokenCoinInfo` is needed here

2024-09-27 17:05 UTC, dessaya commented on packages/vm/execution/common.go
> +	return "", nil, fmt.Errorf("native processor not found for programHash")
This should probably be one of `coreerrors`

2024-10-01 14:56 UTC, cwarnerdev commented on packages/origin/origin.go
> +	accounts.NewStateWriter(v, accounts.Contract.StateSubrealm(d)).SetInitialState(originDeposit)
oops, messed that up with a merge conflict resolution. thanks!

2024-10-01 15:04 UTC, merged