fix chainclient
iotaledger/wasp pull request #306
Opened 2024-10-10 17:05 UTC by howjmay

2024-10-10 17:10 UTC, lmoe requested changes

2024-10-10 17:10 UTC, lmoe commented on clients/chainclient/chainclient.go
> +	"github.com/iotaledger/wasp/sui-go/sui"
Please use iota-go now

2024-10-17 14:15 UTC, dessaya commented on clients/iota-go/iotago/messages.go
> +func (p ProgrammableTransaction) IsInputObjectExist(targetID *ObjectID) bool {
The name seems confusing. What does `Exist` mean here? Can it just be called `IsInputObject`?

2024-10-17 14:15 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +	args [][]byte,
If `isc` is a lower level package then maybe these 3 should be `msg isc.Message`.

2024-10-17 14:15 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +	allowanceArray []iscmove.CoinAllowance,
And this can just be `*isc.Assets`.

2024-10-17 14:15 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +	"github.com/iotaledger/wasp/packages/isc"
Doesn't this create an import loop? I thought `iscmoveclient` was lower level than `isc`.

2024-10-17 14:15 UTC, dessaya commented on packages/testutil/l1starter/l1starter.go
> +		// "--with-indexer", "--pg-user=postgres", "--pg-password=postgres", "--pg-db-name=postgres",
pls remove this

2024-10-17 14:15 UTC, dessaya commented on packages/vm/core/testcore/sbtests/sbtestsc/interface.go
> -	FuncTestCustomError.WithHandler(testCustomError),
why is this removed?

2024-10-17 14:54 UTC, howjmay commented on clients/iota-go/iotago/messages.go
> +func (p ProgrammableTransaction) IsInputObjectExist(targetID *ObjectID) bool {
The `Inputs` field of `ProgrammableTransaction` is an array. So I want to express whether the object has existed in the array. For me `IsInputObject ` is a little bit confusing too, because is a ObjectID which for sure not a InputObject. Maybe I just need some time to get used to it

2024-10-17 14:58 UTC, howjmay commented on clients/iscmove/iscmoveclient/client_request.go
> +	"github.com/iotaledger/wasp/packages/isc"
`iscmoveclient` is not imported by `iscmove`, so the loop doesnt exist

2024-10-17 15:13 UTC, dessaya commented on clients/l2client.go
> +		msg isc.Message,
Ok but now there is an inconsistency. `CreateAndSendRequestWithAssets` receives parameters from `isc` package while e.g. `CreateAndSendRequest` does not (still receives `iscContractName uint32` instead of `isc.Message`).

I think this happens because we were not supposed to import `isc` from here.

2024-10-17 21:08 UTC, howjmay commented on clients/l2client.go
> +		msg isc.Message,
Should I revert `CreateAndSendRequestWithAssets` to the way `CreateAndSendRequest` is?

2024-10-18 12:22 UTC, dessaya commented on clients/l2client.go
> +		msg isc.Message,
IMO either don't use `isc`, or use it in all functions where it makes sense. Otherwise the inconsistency makes the package harder to use.

2024-10-18 13:25 UTC, howjmay commented on clients/l2client.go
> +		msg isc.Message,
I add similar types in `iscmove/isc.go`, so the interface may look better now

2024-10-18 14:47 UTC, dessaya commented on clients/iscmove/isc.go
> +	"github.com/iotaledger/wasp/packages/coin"
Same issue here: introducing the import `coin` significantly changes the dependency semantics. It is not supposed to be imported from here.

Either that, or maybe it makes sense to make `iscmove` higher-level than both `isc` and `coin`. But in that case we should refactor all types and methods to be defined in terms of `isc` stuff.

2024-10-18 14:47 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +	msg iscmove.Message,
This introduces an inconsistency with `CreateAndSendRequest`, which receives `iscContractName uint32` etc.

2024-10-18 14:47 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +				coin.Balance = iotajsonrpc.NewBigInt(bal.Uint64())
Why change the coin's balance here?

2024-10-18 14:47 UTC, dessaya commented on packages/isc/assets.go
> +func (a *Assets) ToCoinAllowances() []iscmove.CoinAllowance {
If this is no longer necessary then I'd remove it.

2024-10-18 16:09 UTC, howjmay commented on clients/iscmove/isc.go
> +	"github.com/iotaledger/wasp/packages/coin"
Isnt it ok to treat `coin` package as lower level or the same level as `iscmove`? The dependency of coin package is clear.

2024-10-18 16:10 UTC, howjmay commented on clients/iscmove/iscmoveclient/client_request.go
> +	msg iscmove.Message,
I can change the interface of `CreateAndSendRequest `too.

2024-10-18 16:15 UTC, howjmay commented on clients/iscmove/iscmoveclient/client_request.go
> +				coin.Balance = iotajsonrpc.NewBigInt(bal.Uint64())
We will use the `coins` array as the parameter of `PTBAssetsBagPlaceCoinWithAmount()`. The balance of the coin is used as a separate parameter in that function to specify the amount to put into the AssetsBag.
And the ObjectRef in the coin object is used to make the coin object as a CallArg in the ptb. They are independent here

2024-10-23 11:55 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +				coin.Balance = iotajsonrpc.NewBigInt(bal.Uint64())
IMO this is a bit hacky... It's confusing because it's changing the `Balance` of a `Coin` that has an `ObjectID`, which seems prone to subtle bugs. I think it's better if we can solve this without mutating the coins.

2024-10-23 11:55 UTC, dessaya commented on clients/iscmove/isc.go
> +	"github.com/iotaledger/wasp/packages/coin"
No, I think `coin` is on the same level as `isc`. It is separated only because of some import loop.

So IMO we have to choose:

1) Do not import `isc` or `coin` from here
2) Import them, but also refactor all types and methods to be defined in terms of `isc` stuff.

I'm fine either way, but not with something in the middle which is inconsistent.

Maybe @lmoe has a different opinion

2024-10-23 12:41 UTC, lmoe commented on clients/iscmove/isc.go
> +	"github.com/iotaledger/wasp/packages/coin"
No I agree, it's important to find a decision between two and I would lean towards 1. As Diego said, coin was moved out of the isc package due to some import loop. 

iscmove/isc.go as you can see does not use any isc functions and types except in tests. -> For example we don't use isc.Hname but uint32s to have the least amount of coupling between isc internals.

I know it seems nicer and easier to just return a CoinBalance with typed values from that package but I think that will bite us later.

If I were you, I would create a type alias CoinBalances as map[string]uint64 and deal with the handling on the callers side. Maybe add a "NewAssetsFromCoinBalances" if we don't have it already. 

/cc @dessaya

2024-10-23 13:29 UTC, howjmay commented on clients/iscmove/iscmoveclient/client_request.go
> +				coin.Balance = iotajsonrpc.NewBigInt(bal.Uint64())
I created a new coin and append to the array `placedCoins`. I think this may be more clear

2024-10-23 13:31 UTC, howjmay commented on clients/iscmove/isc.go
> +	"github.com/iotaledger/wasp/packages/coin"
I have decoupled `coin` from `iscmove` package

2024-10-28 12:40 UTC, dessaya commented on clients/iscmove/isc.go
> +var baseTokenType = "0x2::iota::IOTA"
No need to redefine, it's in `iotajsonrpc.IotaCoinType`

2024-10-28 12:40 UTC, dessaya commented on clients/iota-go/iotago/messages.go
> +func (p ProgrammableTransaction) DoesObjectIdExistInInputObjects(targetID *ObjectID) bool {
Nitpicking, but in Go the convention is `ID` instead of `Id`:

```suggestion
func (p ProgrammableTransaction) DoesObjectIDExistInInputObjects(targetID *ObjectID) bool {
```

Also, a bit shorter: `IsObjectIDInInputObjects`

Or even: `IsInInputObjects`

2024-10-28 12:40 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +				coin.Balance = iotajsonrpc.NewBigInt(bal.Uint64())
The coin is still being mutated. I think you forgot to remove the line.

2024-10-28 12:40 UTC, dessaya commented on clients/iscmove/iscmoveclient/client_request.go
> +				})
It's still strange that you are creating an instance of `iotajsonrpc.Coin`, which represents a L1 coin with an ObjectID, and assigning the ObjectID of an existing coin and a different balance. It doesn't really solve the problem that using `iotajsonrpc.Coin` for this purpose is incorrect.

IMO `placedCoins` should be a different type, for example:

```
placedCoins := []lo.Tuple[*iotajsonrpc.Coin, uint64]
```

i.e. a tuple where the first value is the original **unchanged** coin and the second the desired balance for splitting.

2024-10-28 17:43 UTC, howjmay commented on clients/iscmove/iscmoveclient/client_request.go
> +				})
fixed!

2024-10-28 17:43 UTC, howjmay commented on clients/iota-go/iotago/messages.go
> +func (p ProgrammableTransaction) DoesObjectIdExistInInputObjects(targetID *ObjectID) bool {
changed!

2024-10-29 13:52 UTC, dessaya approved these changes
:tada:

2024-10-29 13:58 UTC, lmoe approved these changes

2024-10-29 13:58 UTC, lmoe commented
Awesome :)

2024-10-29 15:08 UTC, merged